# Generated by Django 5.2.12 on 2026-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0002_projectbrief_existing_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectbrief',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
