# Generated by Django 5.2.1 on 2025-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sv', models.CharField(max_length=100, verbose_name='Titel (svenska)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (English)')),
                ('description_sv', models.TextField(verbose_name='Beskrivning (svenska)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome-ikon, t.ex. 'fa-solid fa-globe'", max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Synlig')),
            ],
            options={
                'verbose_name': 'Tjänst',
                'verbose_name_plural': 'Tjänster',
            },
        ),
    ]
