# Generated by Django 5.2.1 on 2025-09-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_info_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_info_sv',
            field=models.TextField(blank=True, null=True),
        ),
    ]
