# Generated by Django 5.2.1 on 2025-09-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_extra_info_en_service_extra_info_sv'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Pris i SEK'),
        ),
    ]
