# Generated by Django 5.2.1 on 2025-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_service_order_alter_service_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order', 'title_sv'], 'verbose_name': 'Tjänst', 'verbose_name_plural': 'Tjänster'},
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sorteringsordning'),
        ),
    ]
