# Generated by Django 5.2.12 on 2026-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_siteanalysis_language'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='siteanalysis',
            name='analysis_url_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='siteanalysis',
            name='analysis_ip_created_idx',
        ),
        migrations.AddField(
            model_name='siteanalysis',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=253),
        ),
        migrations.AddField(
            model_name='siteanalysis',
            name='score_accessibility',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteanalysis',
            name='score_headers',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
