# Generated by Django 5.2.12 on 2026-05-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_remove_siteanalysis_analysis_url_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteanalysis',
            name='consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteanalysis',
            name='email_form_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteanalysis',
            name='email_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteanalysis',
            name='followup_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteanalysis',
            name='marketing_consent',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
