# Generated by Django 5.2.1 on 2025-05-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sv', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('description_sv', models.TextField()),
                ('description_en', models.TextField()),
                ('technologies', models.CharField(help_text='Ex: Django, JavaScript, Bootstrap', max_length=200)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
