# Generated by Django 6.0.7 on 2026-09-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Används för sortering, t.ex. första dagen i månaden', verbose_name='Datum')),
                ('title_sv', models.CharField(help_text="T.ex. 'CRM'", max_length=100, verbose_name='Rubrik (svenska)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Rubrik (engelska)')),
                ('description_sv', models.TextField(verbose_name='Beskrivning (svenska)')),
                ('description_en', models.TextField(verbose_name='Beskrivning (engelska)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorteringsordning')),
                ('is_active', models.BooleanField(default=True, verbose_name='Synlig')),
            ],
            options={
                'verbose_name': 'Byggloggspost',
                'verbose_name_plural': 'Byggloggsposter',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ToolCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_sv', models.CharField(max_length=100, verbose_name='Titel (svenska)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (English)')),
                ('description_sv', models.TextField(verbose_name='Beskrivning (svenska)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('icon', models.CharField(blank=True, help_text="Font Awesome-ikon, t.ex. 'fas fa-comments'", max_length=50)),
                ('status', models.CharField(choices=[('live', 'Live'), ('forging', 'I smedjan'), ('development', 'Under utveckling')], default='live', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(blank=True, help_text="Endast relevant för 'I smedjan' / 'Under utveckling'", null=True, verbose_name='Utveckling (%)')),
                ('features_sv', models.TextField(blank=True, help_text="En rad per punkt. Börja raden med '-' för punkter som INTE är klara ännu.", verbose_name='Punktlista (svenska)')),
                ('features_en', models.TextField(blank=True, help_text="One line per item. Start the line with '-' for items that are NOT done yet.", verbose_name='Punktlista (engelska)')),
                ('link_url', models.URLField(blank=True, verbose_name='Läs mer-länk (valfri)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorteringsordning')),
                ('is_active', models.BooleanField(default=True, verbose_name='Synlig')),
            ],
            options={
                'verbose_name': 'Verktygskort',
                'verbose_name_plural': 'Verktygskort',
                'ordering': ['order', 'id'],
            },
        ),
    ]
